export const ADD = "ADD";

export const UPDATE_USERNAME = "UPDATE_USERNAME";

export const INIT_WISHLIST = "INIT_WISHLIST";
export const SET_WISHLIST = "SET_WISHLIST";
export const FETCH_WISHLIST_FAILED = "FETCH_WISHLIST_FAILED";
export const PURCHASE = "PURCHASE";
export const SELECT_ITEM = "SELECT_ITEM";